### PR TITLE
Add recommendations in finetuning notebook

### PR DESCRIPTION
**Pull request by anwai98**
I've added the following recommendations to the finetuning notebook:
- To ignore constructor argument warnings while finetuning the model
- Added sampler to the loader, with a mention on when and why samplers are needed.
- Added suggestion to finetune SAM with our conv. decoder with densely annotated labels.

Looks like diff is not available even with `nbconvert` tricks in `jupyter`. I'll see if I can integrate [ReviewNB](https://www.reviewnb.com/) in `micro-sam`.

### CODE REVIEW

**Comment by anwai98** [comment]
Also takes care of https://github.com/computational-cell-analytics/micro-sam/issues/713

**Comment by constantinpape** [comment]
> Looks like diff is not available even with `nbconvert` tricks in `jupyter`. I'll see if I can integrate [ReviewNB](https://www.reviewnb.com/) in `micro-sam`.

I have approved this. Can you check if it works now?

**Comment by anwai98** [comment]
Yes, this works as expected, and is indeed quite impressive. Thanks!

**Comment by anwai98** [comment]
https://app.reviewnb.com/computational-cell-analytics/micro-sam/pull/720/

**Comment by anwai98** [comment]
I have now added the following:
- Filter out raised warnings
- Add quiet argument for download and unzip scripts wherever possible (besides the one from `pooch.retrieve` - the console outputs seem to still be there)

PS. I really like the notification from reviewnb bot to check the notebook diff.

The notebook should be good to go from my side. Let me know if we would like to add few more recommendations!

**Review by constantinpape — APPROVED** [review]

**Pull request merged**
