### PR TITLE
Update environment_cpu.yaml

### PR DESCRIPTION
**Pull request by constantinpape**

### CODE REVIEW

**Comment by anwai98** [comment]
Out of curiousity, doesn't `magicgui` come with `napari`'s install?
I just tried installing `napari` (using `mamba install -c conda-forge napari`), and looks like it does bring in the `magicgui` package to install together.

**Review by GenevieveBuckley — APPROVED** [review]

**Comment by constantinpape** [comment]
Just fyi, I started to work on this to make installation easier, e.g. to solve issues in #407. It looks like the immediate problems there are fixed, but I will get back to the PR here soon.

**Comment by anwai98** [comment]
@Sagnik700 Here's the WIP on your reported issue (regarding adding `pyqt` to the installation scripts).

**Comment by constantinpape** [comment]
Closed in favor of https://github.com/computational-cell-analytics/micro-sam/commit/46aa5d45fa816aab6f64af8700af61781ed1a6a4

**Pull request closed without merging**
