### PR TITLE
Add documentation using docstrings and types

### PR DESCRIPTION
**Pull request by Jujhar**
For #71
I added pdoc it should be very easy and straightforward to use.

### CODE REVIEW

**Comment by constantinpape** [comment]
Thanks for looking into this: I will have a look into `pdoc` and see if it's suitable.
One comment though: the auto-generated files should ideally not be added to `master`, but instead to a special branch from which the doc is rendered (typically `gh-pages`).

**Comment by Jujhar** [comment]
Could you create that branch I don't think I have the permissions.
I'll update the PR then.

**Comment by constantinpape** [comment]
Thanks for looking into this @Jujhar ! I will need a few days before I have time to evaluate whether `pdoc` is suitable. I will come back to you about this then.

**Comment by constantinpape** [comment]
Hi @Jujhar,
I looked into this now, and I think `pdoc` is a great choice, and meets all our requirements. Thanks for suggesting it, and for starting to contribute.
I have prepared the following now:
- There is now a `gh-pages` branch, which we can use to deploy the documentation.
    - The rendered website will then be available at https://computational-cell-analytics.github.io/micro-sam/ (currently just a dummy)
    - The `pdoc` documentation also explains how to deploy to `gh-pages`: https://pdoc.dev/docs/pdoc.html#deploying-to-github-pages (I just skimmed it, but seems to be straightforward)
- Including more documentation from markdown is also simple, see `... include Markdown files?` in the pdoc documentation.
- I will work on a PR where I will prepare a few things for the documentation:
    - Add a folder `doc` for all additional documentation material (markdown and images / gifs).
    - Standardize the doc strings:
         - We will follow the [google docstring style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)
         - But use type annotation in all relevant function signatures instead of documenting the types in the doc string.

I will work on the content (creating some initial markdown files, creating and standardizing doc-strings + type annotations) in the next few days.
When you have time you can already look into adapting the doc generation code to what I described here. Let me know if you have any questions, and thanks again for contributing!

**Comment by constantinpape** [comment]
I have merged #80 now, so the base things for the documentation are there.

**Comment by constantinpape** [comment]
Hi @Jujhar ,
I went ahead and implemented the CI for the documentation here: #88.
Thanks for suggesting `pdoc`!

**Comment by Jujhar** [comment]
Hi @constantinpape, was out of town let me know for anything related to this or CI or automation in general (particularly advanced or very difficult things)

**Pull request closed without merging**
