### PR TITLE
Add M1 MacOS runner to github actions jobs

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Closes https://github.com/computational-cell-analytics/micro-sam/issues/369

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

> ## GitHub Actions: Introducing the new M1 macOS runner available to open source!
>    January 30, 2024
>
> Today, GitHub is excited to announce the launch of a new M1 macOS runner! This runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner executes Actions workflows with a 3 vCPU, 7 GB RAM, and 14 GB of storage VM, which provides the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the `runs-on` key in your YAML workflow file to `macos-14`.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Question: do we want to remove `macos-latest`, and keep only `macos-14`? Or keep both, until `macos-latest` finally does catch up to using `macos-14` by default (probably some time away). For now, I've kept both.

It seems that currently, `macos-latest` gives you `macos-12` ([see the official table here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners), and the most recent [announcement post I could find about it on the github blog](https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/).

**Comment by constantinpape** [comment]
Thanks for working on this @GenevieveBuckley! Let's keep `macos-latest` around until it catches up to `macos-12`.  
I have identified the reason for the test failure #371 and I will look into fixing it in the evening.

**Comment by constantinpape** [comment]
I fixed #373 @GenevieveBuckley. Once you merge `dev` here the test failure should be gone.

**Comment by GenevieveBuckley** [comment]
Oh no, memory problems

```
FAILED test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box - RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes, max allowed: 7.93 GB). Tried to allocate 256 bytes on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
```

The `macos-14` runner has 3 M1 cpus, 7 GB of RAM, and 14 GB SSD storage.

We can either mark some of the tests as memory hungry, and skip them on the `macos-14` runner,
OR try to make the tests smaller (depending on what they are, this could be difficult).

I also saw that [according to this page](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/):
* there are large and extra large versions for the new M1 mac runners, but these are only for paid users (Github Teams and Enterprise)
* they are hoping to upgrade macos-latest to use macos-14 sometime around April to June 2024

**Comment by constantinpape** [comment]
> Oh no, memory problems

It is a bit strange that this test runs out of memory. The test data for this is tiny, a 10x10 array with a single binary mask:

https://github.com/computational-cell-analytics/micro-sam/blob/master/test/test_vendored.py#L11-L15

Maybe something in https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/_vendored.py#L29 is still very memory inefficient on MPS?! 

If you have time you could maybe memory profile it on MPS again? Otherwise we have to skip this test in CI.

**Comment by constantinpape** [comment]
@GenevieveBuckley I only see memory profiles for some of the tests:

- Allocation results for test/test_sam_annotator/test_widgets.py::test_embedding_widget at the high watermark
- Allocation results for test/test_sam_annotator/test_annotator_2d.py::test_annotator_2d at the high watermark
- Allocation results for test/test_sam_annotator/test_annotator_3d.py::test_annotator_3d
- Allocation results for test/test_sam_annotator/test_image_series_annotator.py::test_image_folder_annotator
- Allocation results for test/test_sam_annotator/test_annotator_tracking.py::test_annotator_tracking

Could you maybe rerun it only for `TestVendored::test_mps_batched_mask_to_box ` and post the memory benchmark? I think that will help better to see if there is a memory spike.

**Comment by GenevieveBuckley** [comment]
> I only see memory profiles for some of the tests

Yes, that's what I see too. I can't make it produce any more information than that.

* I tried asking pytest for more verbose output  (`pytest -vv --memray`), but the memray report section did not show more information.
* I tried adjusting the `--most-allocations` pytest-memray [configuration option](https://pytest-memray.readthedocs.io/en/latest/configuration.html). I used both `--most-allocations=0` (which should show everything) and `--most-allocations=34` (the number of tests collected by pytest)


> Could you maybe rerun it only for `TestVendored::test_mps_batched_mask_to_box` and post the memory benchmark? I think that will help better to see if there is a memory spike.

I'm sorry, when I tried this earlier there was no output. The "MEMRAY REPORT" section heading still appears in the pytest output, but no contents below it and the next lines of text are the test coverage information. Here's a copy of those (lack of) results:

<details>
<summary>Details (click to expand)</summary>

```
pytest -vv --memray test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box
```

```python-traceback
======================================== test session starts =========================================
platform darwin -- Python 3.11.7, pytest-8.0.0, pluggy-1.4.0 -- /Users/genevieb/mambaforge/envs/micro-sam-dev/bin/python3.11
cachedir: .pytest_cache
PyQt5 5.15.10 -- Qt runtime 5.15.12 -- Qt compiled 5.15.11
rootdir: /Users/genevieb/Documents/GitHub/micro-sam
configfile: pyproject.toml
plugins: cov-4.1.0, napari-plugin-engine-0.2.0, qt-4.3.1, napari-0.4.19, memray-1.5.1.dev12+g1549d62, npe2-0.7.3
collected 1 item

test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box PASSED                       [100%]


=========================================== MEMRAY REPORT ============================================

---------- coverage: platform darwin, python 3.11.7-final-0 ----------
Name                                                Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------
micro_sam/__init__.py                                   3      0   100%
micro_sam/__version__.py                                1      0   100%
micro_sam/_test_util.py                                11     11     0%   1-22
micro_sam/_vendored.py                                 85     46    46%   17-21, 43, 49, 77, 86-97, 101-107, 122-150
micro_sam/evaluation/__init__.py                        4      4     0%   4-17
micro_sam/evaluation/evaluation.py                     32     32     0%   5-75
micro_sam/evaluation/experiments.py                    28     28     0%   4-83
micro_sam/evaluation/inference.py                     226    226     0%   4-603
micro_sam/evaluation/instance_segmentation.py         135    135     0%   4-386
micro_sam/evaluation/livecell.py                      172    172     0%   5-415
micro_sam/evaluation/model_comparison.py              236    236     0%   4-435
micro_sam/inference.py                                 60     60     0%   1-148
micro_sam/instance_segmentation.py                    383    383     0%   7-962
micro_sam/multi_dimensional_segmentation.py           102    102     0%   4-259
micro_sam/precompute_state.py                          72     72     0%   4-182
micro_sam/prompt_based_segmentation.py                200    200     0%   5-499
micro_sam/prompt_generators.py                        129    129     0%   6-350
micro_sam/sam_annotator/__init__.py                     4      4     0%   4-7
micro_sam/sam_annotator/_annotator.py                  70     70     0%   1-160
micro_sam/sam_annotator/_state.py                      69     69     0%   6-140
micro_sam/sam_annotator/_widgets.py                   237    237     0%   4-516
micro_sam/sam_annotator/annotator_2d.py                37     37     0%   1-109
micro_sam/sam_annotator/annotator_3d.py                57     57     0%   1-133
micro_sam/sam_annotator/annotator_tracking.py         105    105     0%   1-275
micro_sam/sam_annotator/gui_utils.py                   41     41     0%   1-75
micro_sam/sam_annotator/image_series_annotator.py      88     88     0%   1-227
micro_sam/sam_annotator/util.py                       266    266     0%   1-543
micro_sam/sample_data.py                              145    145     0%   15-378
micro_sam/training/__init__.py                          3      3     0%   4-6
micro_sam/training/joint_sam_trainer.py               127    127     0%   1-200
micro_sam/training/sam_trainer.py                     221    221     0%   1-447
micro_sam/training/trainable_sam.py                    44     44     0%   1-128
micro_sam/training/util.py                            107    107     0%   1-236
micro_sam/util.py                                     363    363     0%   5-841
micro_sam/visualization.py                             92     92     0%   4-169
---------------------------------------------------------------------------------
TOTAL                                                3955   3912     1%
Coverage XML written to file coverage.xml

======================================== slowest 10 durations ========================================
0.16s call     test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box
0.05s setup    test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box
0.00s teardown test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box
========================================= 1 passed in 2.09s =========================================
```

</details>

I don't know if the reason for this is that the test actually doesn't use much memory at all (like you expect). Maybe there are memory leaks elsewhere, and this test just happens to be when  the memory is full, but not the cause?

I tried to test this by adding the [pytest-memray marker to limit leaks](https://pytest-memray.readthedocs.io/en/latest/usage.html#pytest.mark.limit_leaks) `@pytest.mark.limit_leaks("1 MB")` to all our test functions. Surprisingly, there was no error/failure/crash/warning when I ran the tests again. But I am still not sure if this sufficiently tests the hypothesis - there are a lot of setup and tear down actions not covered by the markers & I don't know if they could be leaking.

Other things we could try:
1. Try adding the limit leak marker to the setup and teardown functions, and/or maybe the test classes as well. I don't know if this will work, or break things, but it seems easy enough to try.
2. Convert the test case into a plain python script, and run it using memray directly (not pytest-memray). Maybe then we will be able to get detailed output about `test_mps_batched_mask_to_box`
3. We could also make a new branch, with another github actions script including a `workflow_dispatch` manual trigger, that exists just so we can try running pytest on smaller sections or different combinations of the tests. That would be annoying, but perhaps we could narrow down where the problem comes from?

**Comment by GenevieveBuckley** [comment]
Getting closer. I made a mistake with my earlier memory leak tests, and forgot to decorate the files `test/test_sam_annotator`. The memory leaks are happening in all the places where we run the annotator (which sets up a model, the AnnotatorState, etc.). Files affected are:
* `test_annotator_2d.py`
* `test_annotator_3d.py`
* `test_annotator_tracking.py`
* `test_image_series.py`

I'm trying to reduce the problem by deleting variables, running the garbage collector, and emptying the pytorch cache. That seems to help a bit, but it's not great yet.

**Comment by GenevieveBuckley** [comment]
Here's a test, we'll see if this helps the `macos-14` CI memory problems: https://github.com/GenevieveBuckley/micro-sam/pull/5

**Comment by constantinpape** [comment]
> The memory leaks are happening in all the places where we run the annotator (which sets up a model, the AnnotatorState, etc.). Files affected are:

Ok, that's good to know! This might point to a problem with the napari test infrastructure though?!

> EDIT: the changes don't seem to have made any difference 😢

That's too bad :(.


I still find it curious that it's always `test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box`  that fails...

For now, I suggest we skip this test and go ahead with the PR.

**Comment by GenevieveBuckley** [comment]
> This might point to a problem with the napari test infrastructure though?!

I don't think so? I think that because:
1. The `make_napari_viewer_proxy` test fixture was created to avoid those potential problems ([see here](https://napari.org/stable/plugins/test_deploy.html#the-make-napari-viewer-proxy-fixture)). 
2. Also, the `test_widgets.py` tests do **not** report memory leaks using the pytest-memray decorator. This test just opens napari and adds the plugin dock widget, but doesn't do any processing/computation with micro-sam. That's the other reason I suspect something created by micro-sam might still be hogging memory somewhere (like the model, annotator state, torch cache, ...something else?)

> I still find it curious that it's always test/test_vendored.py::TestVendored::test_mps_batched_mask_to_box that fails...

I don't think this is curious. The tests are always collected and run in the same order
We could try:
* Renaming `test_vendored.py` to `test_aaa_vendored.py` to see if I can get that test to run first, not last, and see if it still fails, or
* Looking for a pytest plugin that randomizes the order of tests. I'm sure one must exist (I've just found [pytest-randomly](https://pypi.org/project/pytest-randomly/) and [pytest-random-order](https://pypi.org/project/pytest-random-order/), looks like there are quite a few options to choose from). Then we can see if the same test fails or not.

**Comment by GenevieveBuckley** [comment]
You're right - it doesn't matter which order the tests run in (thanks [pytest-randomly]()), `TestVendored::test_mps_batched_mask_to_box` always fails on the `macos-14` CI. 

That is very weird.

**Comment by GenevieveBuckley** [comment]
I give up. I do not know why that test fails. I've made an issue here: https://github.com/computational-cell-analytics/micro-sam/issues/380 and have skipped the test if it is running on github actions.

**Comment by constantinpape** [comment]
My best guess is the following:
- We do have some memory leaks in the widget tests. Not sure if they are due to napari, or pytorch. (This might also be due to pytorch MPS, I do have the feeling that this is still quite experimental...)
- In addition the `test_mps_batched...` takes a lot of memory, because there is some memory inefficiency in MPS.

In any case, thanks for looking into this!! At least we now know that these issues are there.

**Pull request merged**
