### PR TITLE
Minor update to object import in training scheme

### PR DESCRIPTION
**Pull request by anwai98**
@constantinpape Minor fix to an issue I encountered, should be GTG!

### CODE REVIEW

**Comment by constantinpape** [comment]
Just fyi, I would rather fix this with updating the dependencies. Will leave it open for now as a reminder.

**Comment by constantinpape** [comment]
The PR with the dependency update for this is merged (both here and on conda-forge), so I am closing this.

**Comment by anwai98** [comment]
I'll go ahead and close this then. Thanks!

**Comment by anwai98** [comment]
@constantinpape For running scripts using python modules, I think we don't need the `qtpy` import mandatorily on top, in cases not desired. I am guessing this should wrap around a try-catch to avoid encountering issues? (I mention this because I faced this recently while loading the model checkpoints)

**Comment by constantinpape** [comment]
@anwai98 yeah, this makes sense. I think we should merge this to keep the training independent of qt. I will merge it once the tests pass.

**Pull request merged**
