### PR TITLE
Add FAQ section

### PR DESCRIPTION
**Pull request by anwai98**

### CODE REVIEW

**Comment by constantinpape** [comment]
I had a quick look and the FAQ looks good so far. Just let me know when it's ready from your side @anwai98, I will then merge it and read over it again and change some formulations while finalizing the docs.

**Comment by anwai98** [comment]
This is ready to review from my side!

One minor mention:
- I left a question for you to take a look at: under `Usage` -> Point `6.`

Thanks!

**Comment by constantinpape** [comment]
Thanks @anwai98 ! I will take care of the merge conflicts and include this file in #568 .

**Comment by constantinpape** [comment]
Closed in favor of #568 which now includes this file (to avoid the merge conflicts).

**Pull request closed without merging**
