### PR TITLE
CI testing - automatic code coverage reports

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
This PR investigates adding code coverage reports to the CI.

Included in this PR:
* Switch to pytest (previously unittest was used)
* Generate code coverage reports (using pytest-cov)
* Uploads code coverage to codecov.io
* Reduces duplication of CI runs, by adjusting the triggers for the github actions workflow
* Switches to micromamba for the CI (instead of miniconda combined with mamba). This creates our test environment in about half the time that miniconda did. It saves about a quarter of the overall CI job time (there aren't a lot of tests right now, so the environment setup is a large proportion of the CI runtime)

When this PR is ready to merge:
1. We'll need to add a secret key to the repository, so the upload to codecov.io can happen automatically, and
2. We should absolutely consider squash merging this PR, the commit history is very messy

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
> > We'll need to add a secret key to the repository, so the upload to codecov.io can happen automatically.
>
> Ok! Do you have enough permissions here to do this, or do I need to create the key?

No, I don't have permissions to do that. You'd need to go into [this section of the settings](https://github.com/computational-cell-analytics//micro-sam/settings/secrets/actions) to add a `CODECOV_TOKEN` repository secret, the contents of the secret is whatever codecov tells you when you set up the repository: https://about.codecov.io/product/getting-started/

But his is all a bit premature, because for some reason I can't get codecov to actually find and upload the file! Here's me testing things unsuccessfully: https://github.com/GenevieveBuckley/micro-sam/pull/1#issuecomment-1736890023

**Comment by constantinpape** [comment]
Thanks for the link @GenevieveBuckley , I will add the token at some point today.

**Comment by GenevieveBuckley** [comment]
Ok, I [figured out the problem](https://github.com/GenevieveBuckley/micro-sam/pull/1#issuecomment-1746011859), and now it's working well. This PR is now ready for review & merge.

Test coverage of the `micro_sam` directory is ~16%. You can play around with the results here: https://app.codecov.io/github/GenevieveBuckley/micro-sam/pull/1/tree/micro_sam

You can also run `pytest` on your local repository, and it will generate the `coverage.xml` output automatically. Then you can use the [VSCode Coverage Gutters extension](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) (or similar) to easily see which lines of code are not covered by the tests.

**Comment by constantinpape** [comment]
Hi @GenevieveBuckley ,
I have added the codecov secret now:
image
so I think codecov should be able to upload the test reports once we merge this.

From my end this can be merged once the conflict is fixed and the commits are squashed. Let me know if you need anything from my end for this!

**Comment by GenevieveBuckley** [comment]
Fixed! I think this is ready for merge now @constantinpape

**Comment by GenevieveBuckley** [comment]
Hmm, I don't love that codecov isn't already uploading the coverage information. I think that *should* be happening now, even before merging.

<details>
<summary>Details (click to expand)</summary>

```
Codecov report uploader 0.6.3
[2023-10-16T01:31:05.677Z] ['info'] => Project root located at: /home/runner/work/micro-sam/micro-sam
[2023-10-16T01:31:05.679Z] ['info'] -> No token specified or token is empty
[2023-10-16T01:31:05.689Z] ['info'] Searching for coverage files...
[2023-10-16T01:31:05.749Z] ['info'] => Found 1 possible coverage files:
  ./coverage.xml
[2023-10-16T01:31:05.750Z] ['info'] Processing ./coverage.xml...
[2023-10-16T01:31:05.755Z] ['info'] Detected GitHub Actions as the CI provider.
[2023-10-16T01:31:05.946Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.4-uploader-0.6.3&token=*******&branch=codecov-report&build=6527844768&build_url=https%3A%2F%2Fgithub.com%2Fcomputational-cell-analytics%2Fmicro-sam%2Factions%2Fruns%2F6527844768&commit=d44878227ddd77920ec487ec1b5ecb46e34c38d9&job=test&pr=214&service=github-actions&slug=computational-cell-analytics%2Fmicro-sam&name=&tag=&flags=&parent=
[2023-10-16T01:31:06.139Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

</details>

**Comment by GenevieveBuckley** [comment]
It works! 🎉 🎉 🎉 

You can [see it on codecov here](https://app.codecov.io/gh/computational-cell-analytics/micro-sam/pull/214/tree/micro_sam). Your new secret token works.

Note: this is purely for information - the CI build will not fail if codecov fails to upload the results, and we also won't flag any PRs that decrease code coverage. But it will be useful in the future, to see what to target to improve the test suite most effectively.

**Comment by GenevieveBuckley** [comment]
Lessons learnt: it is better to pass your secret token in to the `with` argument, and not `env`.
Like this (which is actually [how they say you should use it](https://github.com/codecov/codecov-action#usage)):
```yaml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          verbose: false
          fail_ci_if_error: false
```

**Review by constantinpape — APPROVED** [review]
Thanks @GenevieveBuckley! I will go ahead and "squash and merge" (just realized that github supports this now, so no need for you to manually squash commits)

**Pull request merged**
